stages:
- test

testAuto:
    stage: test
    image: registry.gitlab.com/ccla/devsecops/templates-ci-cd/golden-image/special-image:stable-openjdk-11-maven-3.8.5-alpine-3.16
    services:
    - name: selenium/standalone-chrome:latest
      alias: standalone-chrome
    tags:
    - ccla-private-runners
    variables: 
        MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    cache:
        key: "pipeline-$CI_PROJECT_DIR"
        paths:
        - .m2/repository
    before_script:
    - ping -c 5 pwpwebqaohs.cajalosandes.cl
    script:
    - mvn clean test -PRegression
    artifacts:
        paths:
        - reports/
        expire_in: 1 hour
    rules:
    - if: '$CI_COMMIT_BRANCH'
    